-- 1. Buat Role (Peran) khusus untuk dbt
CREATE ROLE DBT_ROLE;

-- 2. Beri DBT_ROLE izin untuk menggunakan Warehouse
GRANT USAGE ON WAREHOUSE NETFLIX_WH TO ROLE DBT_ROLE;

-- 3. Beri DBT_ROLE izin untuk menggunakan Database
GRANT USAGE ON DATABASE NETFLIX_DATASET TO ROLE DBT_ROLE;

-- 4. Beri DBT_ROLE izin untuk membaca data dari schema RAW
GRANT USAGE ON SCHEMA NETFLIX_DATASET.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NETFLIX_DATASET.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NETFLIX_DATASET.RAW TO ROLE DBT_ROLE; -- Izin untuk tabel baru

-- 5. Beri DBT_ROLE izin untuk membuat schema baru (misal: schema 'ANALYTICS')
GRANT CREATE SCHEMA ON DATABASE NETFLIX_DATASET TO ROLE DBT_ROLE;

-- 6. Buat User khusus untuk dbt
-- GANTI 'password-super-rahasia-anda' DENGAN PASSWORD YANG KUAT
CREATE OR REPLACE USER DBT_USER
  PASSWORD = 
  DEFAULT_ROLE = DBT_ROLE
  DEFAULT_WAREHOUSE = 'NETFLIX_WH';

-- 7. Berikan Role tadi ke User dbt
GRANT ROLE DBT_ROLE TO USER abi;